name: Django Blog CI/CD

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install django pypdf Pillow

    - name: Run migrations & check system
      run: |
        cd my_site
        python manage.py check
        python manage.py makemigrations
        python manage.py migrate

    - name: Populate Database with fixtures
      run: |
        cd my_site
        python manage.py loaddata blog/fixtures/initial_data.json

    - name: Generate pydoc documentation
      run: |
        # Generate pydoc for blog app and display it
        cd my_site
        python -m pydoc blog
